//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Flash_Cards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word_Flash_Cards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_pointed_Star {
            get {
                object obj = ResourceManager.GetObject("_4_pointed_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_pointed_Star {
            get {
                object obj = ResourceManager.GetObject("_5_pointed_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_pointed_Star {
            get {
                object obj = ResourceManager.GetObject("_6_pointed_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Words A to Z
        ///A
        ///Accelerated
        ///Accomplished
        ///Achieved
        ///Acquired
        ///Adapted
        ///Addressed
        ///Administered
        ///Advanced
        ///Advised
        ///Advocated
        ///Analyzed
        ///Applied
        ///Appointed
        ///Arbitrated
        ///Architected
        ///Arranged
        ///Ascertained
        ///Assembled
        ///Assessed
        ///Assisted
        ///Attained
        ///Audited
        ///Authored
        ///Authorized
        ///B
        ///Balanced
        ///Billed
        ///Briefed
        ///Budgeted
        ///Built
        ///C
        ///Calculated
        ///Captured
        ///Carried Out
        ///Cataloged
        ///Championed
        ///Charted
        ///Clarified
        ///Classified
        ///Closed
        ///Coached
        ///Collaborated
        ///Collected
        ///Commanded
        ///Communicated
        ///Compared
        ///Compelled        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Action_Verbs_A_to_Z {
            get {
                return ResourceManager.GetString("Action_Verbs_A_to_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diamond {
            get {
                object obj = ResourceManager.GetObject("Diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolch Sight Words
        ///a
        ///about
        ///after
        ///again
        ///all
        ///always
        ///am
        ///an
        ///and
        ///any
        ///apple
        ///are
        ///around
        ///as
        ///ask
        ///at
        ///ate
        ///away
        ///baby
        ///back
        ///ball
        ///be
        ///bear
        ///because
        ///bed
        ///been
        ///before
        ///bell
        ///best
        ///better
        ///big
        ///bird
        ///birthday
        ///black
        ///blue
        ///boat
        ///both
        ///box
        ///boy
        ///bread
        ///bring
        ///brother
        ///brown
        ///but
        ///buy
        ///by
        ///cake
        ///call
        ///came
        ///can
        ///car
        ///carry
        ///cat
        ///chair
        ///chicken
        ///children
        ///Christmas
        ///clean
        ///coat
        ///cold
        ///come
        ///corn
        ///could
        ///cow
        ///cut
        ///day
        ///did
        ///do
        ///does
        ///dog
        ///doll
        ///done
        ///don’t
        ///door
        ///down
        ///draw
        ///drink
        ///duck
        ///eat
        ///egg
        ///eight
        ///e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dolch_words {
            get {
                return ResourceManager.GetString("Dolch_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down_Arrow {
            get {
                object obj = ResourceManager.GetObject("Down_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hexagon {
            get {
                object obj = ResourceManager.GetObject("Hexagon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Left_Arrow {
            get {
                object obj = ResourceManager.GetObject("Left_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pentagon {
            get {
                object obj = ResourceManager.GetObject("Pentagon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonics
        ///-ab
        ///-ad
        ///-ag
        ///-am
        ///-an
        ///-ap
        ///-at
        ///-ed
        ///-en
        ///-et
        ///-ig
        ///-in
        ///-in
        ///-ip
        ///-it
        ///-ob
        ///-og
        ///-op
        ///-ot
        ///-ub
        ///-ug
        ///-un
        ///-ut
        ///Sh-
        ///Th-
        ///Ch-
        ///-unk
        ///-ink
        ///-ay
        ///-ai
        ///-ee
        ///-ea
        ///-oa
        ///-oo-
        ///duck
        ///-ck  
        ///go
        ///-o 
        ///fly
        ///-y 
        ///say
        ///-ay
        ///stop
        ///st- 
        ///airplane
        ///pl- 
        ///frog
        ///fr- 
        ///train
        ///tr- 
        ///ship
        ///sh- 
        ///thick
        ///th- 
        ///this
        ///th- 
        ///block
        ///bl- 
        ///clock
        ///cl- 
        ///flake
        ///fl- 
        ///glue
        ///gl- 
        ///bride
        ///br- 
        ///drum
        ///dr- 
        ///praise
        ///pr- 
        ///grin
        ///gr- 
        ///smoke
        ///sm- 
        ///scat
        ///sc- 
        ///skate
        ///sk- 
        ///spade
        ///sp-  
        ///crab 
        ///cr- 
        ///twins
        ///tw-   
        ///splash
        ///spl-           /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phonics {
            get {
                return ResourceManager.GetString("Phonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ab
        ///cab
        ///grab
        ///dab
        ///drab
        ///grab
        ///lab
        ///nab
        ///tab
        ///
        ///Sh-
        ///Shark
        ///Sheep
        ///Shop
        ///Shut
        ///She
        ///Shoe
        ///Ship
        ///Shot
        ///Shell
        ///Th-
        ///The
        ///That
        ///They
        ///This
        ///Thumb
        ///Three
        ///There
        ///Think
        ///Thorn
        ///Ch-
        ///Chin
        ///Chomp
        ///Chop
        ///Chug
        ///Chain
        ///Cheer
        ///Chief
        ///Check
        ///Chick
        ///-unk
        ///Skunk
        ///Bunk
        ///Dunk
        ///Junk
        ///Sunk
        ///Shrunk
        ///Stunk
        ///Trunk
        ///chipmunk
        ///-ink
        ///link
        ///pink
        ///sink
        ///wink
        ///blink
        ///drink
        ///stink
        ///ink
        ///think
        ///-ing
        ///king
        ///ring
        ///sing
        ///wing
        ///ding
        ///spring
        ///sting
        ///swing
        ///string
        ///-ay
        ///bay
        ///day
        ///may
        ///ray
        ///say
        ///way
        ///gray
        ///play
        ///tray
        ///-ai
        ///snail
        ///sail
        ///nail [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phonics_Practice {
            get {
                return ResourceManager.GetString("Phonics_Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rectangle {
            get {
                object obj = ResourceManager.GetObject("Rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Right_Arrow {
            get {
                object obj = ResourceManager.GetObject("Right_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Right_Triangle {
            get {
                object obj = ResourceManager.GetObject("Right_Triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Words Level A
        ///a
        ///all
        ///am
        ///and
        ///are
        ///at
        ///ate
        ///away
        ///b
        ///be
        ///bed
        ///big
        ///black
        ///blue
        ///box
        ///brown
        ///but
        ///c
        ///came
        ///can
        ///car
        ///cat
        ///come
        ///d
        ///did
        ///do
        ///dog
        ///down
        ///e
        ///each
        ///eat
        ///egg
        ///f
        ///find
        ///fish
        ///for
        ///fox
        ///four
        ///funny
        ///g
        ///get
        ///go
        ///good
        ///h
        ///have
        ///he
        ///help
        ///here
        ///I
        ///in
        ///into
        ///is
        ///it
        ///J
        ///Jab
        ///jam
        ///jade
        ///jack
        ///jess
        ///jazz
        ///john
        ///joust
        ///K
        ///kangaroo
        ///king
        ///kite
        ///kick
        ///knit
        ///key
        ///leg
        ///like
        ///little
        ///look
        ///make
        ///me
        ///must
        ///my
        ///new
        ///no
        ///not
        ///now
        ///of
        ///on
        ///one
        ///other
        ///our
        ///out
        ///pig
        ///play
        ///pretty
        ///quad
        ///quack
        ///queen
        ///quest
        ///r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SightWordsLevelA {
            get {
                return ResourceManager.GetString("SightWordsLevelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Words Level B
        ///after
        ///again
        ///always
        ///an
        ///any
        ///around
        ///as
        ///ask
        ///baby
        ///ball
        ///because
        ///been
        ///before
        ///bell
        ///best
        ///both
        ///brother
        ///buy
        ///by
        ///call
        ///children
        ///cold
        ///could
        ///day
        ///does
        ///doll
        ///don&apos;t
        ///every
        ///fast
        ///father
        ///first
        ///five
        ///fly
        ///found
        ///from
        ///gave
        ///give
        ///goes
        ///going
        ///green
        ///grandma
        ///grandmother
        ///grandpa
        ///grandfather
        ///had
        ///hand
        ///has
        ///head
        ///her
        ///him
        ///his
        ///how
        ///its
        ///jump
        ///just
        ///know
        ///let
        ///live
        ///made
        ///many
        ///may
        ///more
        ///mother
        ///number
        ///off
        ///old
        ///once
        ///open
        ///or
        ///orange
        ///over
        ///people
        ///please
        ///pull
        ///purple
        ///put
        ///r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SightWordsLevelB {
            get {
                return ResourceManager.GetString("SightWordsLevelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Words Level C
        ///about
        ///air
        ///also
        ///another
        ///answer
        ///back
        ///better
        ///boy
        ///bring
        ///carry
        ///chair
        ///change
        ///clean
        ///coat
        ///cut
        ///different
        ///done
        ///door
        ///draw
        ///drink
        ///during
        ///eight
        ///end
        ///even
        ///fall
        ///far
        ///feet
        ///field
        ///find
        ///floor
        ///follow
        ///full
        ///game
        ///girl
        ///got
        ///great
        ///grow
        ///hard
        ///hold
        ///home
        ///hot
        ///house
        ///hurt
        ///if
        ///keep
        ///kind
        ///land
        ///large
        ///laugh
        ///learn
        ///light
        ///line
        ///long
        ///man
        ///mean
        ///men
        ///money
        ///most
        ///move
        ///much
        ///myself
        ///name
        ///need
        ///never
        ///nine
        ///nothing
        ///oil
        ///oilly
        ///olive
        ///only
        ///own
        ///page
        ///pager
        ///paper
        ///part
        ///pick
        ///pict [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SightWordsLevelC {
            get {
                return ResourceManager.GetString("SightWordsLevelC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array 1 of 5
        ///2
        ///3
        ///4
        ///5 Program should end
        ///
        ///
        ///.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thunder_bolt {
            get {
                object obj = ResourceManager.GetObject("Thunder_bolt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triangle {
            get {
                object obj = ResourceManager.GetObject("Triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UP_Arrow {
            get {
                object obj = ResourceManager.GetObject("UP_Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_1_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_1_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_10_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_10_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_100_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_100_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_2_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_2_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_20_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_20_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_5_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_5_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_50_Dollar {
            get {
                object obj = ResourceManager.GetObject("US_50_Dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_Dime {
            get {
                object obj = ResourceManager.GetObject("US_Dime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_Nickel {
            get {
                object obj = ResourceManager.GetObject("US_Nickel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_Penny {
            get {
                object obj = ResourceManager.GetObject("US_Penny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap US_Quarter {
            get {
                object obj = ResourceManager.GetObject("US_Quarter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocab Builder
        ///Bene
        ///Am
        ///Bell
        ///Pac
        ///Crim
        ///Prob
        ///Grav
        ///Lev
        ///Mania
        ///Psych
        ///Cept
        ///Fin
        ///Ject
        ///Tract
        ///Duc
        ///Duct
        ///Sequ
        ///Amb
        ///Epi
        ///Hyp
        ///Hypo
        ///Therm
        ///Thermo
        ///Poly
        ///Prim
        ///Hom
        ///Homo
        ///Dis
        ///Vor
        ///Carn
        ///Cred
        ///Fid
        ///Curr
        ///Curs
        ///Ped
        ///Flect
        ///Post
        ///Mal
        ///Cata
        ///Prot
        ///Proto
        ///Ante
        ///Ortho
        ///Rect
        ///Eu
        ///Dys
        ///Equ
        ///Quis
        ///Ple
        ///Plen
        ///Metr
        ///Mete
        ///Aud
        ///Son
        ///Err
        ///Ced
        ///Vis
        ///Spect
        ///Voc
        ///Phon
        ///Cur
        ///Peri
        ///Sens
        ///Soph
        ///Port
        ///Pend
        ///Pan
        ///Extra
        ///Phot
        ///Luc
        ///Mor
        ///Mort
        ///Troph
        ///Her
        ///Fug
        ///Csom
        ///Sci
        ///Junct
        ///Part
        ///Mis
        ///Pel
        ///.
        /// </summary>
        internal static string Vocab_builder {
            get {
                return ResourceManager.GetString("Vocab_builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Famlies
        ///-ab
        ///cab
        ///crab
        ///dab
        ///drab
        ///grab
        ///lab
        ///nab
        ///tab
        ///-ad
        ///dad
        ///lad
        ///bad
        ///mad
        ///had
        ///pad
        ///glad
        ///-ag
        ///bag
        ///nag
        ///rag
        ///tag
        ///gag
        ///wag
        ///brag
        ///drag
        ///-am
        ///am
        ///ham
        ///jam
        ///Pam
        ///Sam
        ///yam
        ///Slam
        ///Spam
        ///-an
        ///can
        ///fan
        ///man
        ///pan
        ///ran
        ///tan
        ///than
        ///plan
        ///-ap
        ///cap
        ///gap
        ///lap
        ///tap
        ///nap
        ///map
        ///flap
        ///trap
        ///-at
        ///bat
        ///cat
        ///hat
        ///mat
        ///pat
        ///sat
        ///that
        ///flat
        ///-ed
        ///bed
        ///fed
        ///led
        ///red
        ///shed
        ///Ted
        ///Ned
        ///wed
        ///-en
        ///Ben
        ///den
        ///hen
        ///men
        ///pen
        ///ten
        ///then
        ///when
        ///-et
        ///get
        ///jet
        ///let
        ///met
        ///net
        ///pet
        ///set
        ///yet
        ///-ig
        ///big
        ///dig
        ///fig
        ///jig
        ///pig
        ///rig
        ///wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Word_Familes {
            get {
                return ResourceManager.GetString("Word_Familes", resourceCulture);
            }
        }
    }
}
